# fly.toml app configuration file generated for go-sjc-assist-bot on 2025-01-18T11:49:58-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'go-sjc-assist-bot'
primary_region = 'gru'

[build]

[deploy]
strategy = "rolling"
max_unavailable = 1

[http_service]
internal_port = 443
force_https = false
auto_stop_machines = 'suspend'
auto_start_machines = true
min_machines_running = 0
processes = ['app']
[http_service.concurrency]
type = "requests"
soft_limit = 200
hard_limit = 250
[http_service.http_options.response]
pristine = true

[[vm]]
cpu_kind = 'shared'
cpus = 1
memory_mb = 256
